os: linux
dist: xenial
language: python

stages:
  - Test
  - Publish

install: pip install poetry tox-travis codecov

jobs:
  include:
    - stage: Test
      python: "3.7"
      script: tox
    - python: "3.8"
      script: tox

    - stage: Publish
      script: skip
      before_deploy:
        - poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
        - poetry build -f sdist
      deploy:
        provider: script
        script: poetry publish
        skip_cleanup: true
        on:
          tags: true
      if: tag IS present